name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.12.x']

    steps:
      - name: 🛒 Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: ⚒️ Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: 📦 Install Dependencies
        # https://github.com/storybookjs/builder-vite/issues/55
        run: npm run bootstrap --shamefully-hoist

      - name: 🚦 Lint
        run: pnpm run lint

      - name: 🔨 Build
        run: pnpm run build

      - name: 🧪 Test
        run: |
          npx playwright install-deps chromium
          pnpm run --filter @this/example build
          pnpm run test:ci

      - name: 🛫 Upload Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
