name: CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: ⚒️ Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: 📦 Install Dependencies
        run: npm run bootstrap

      - name: 🚦 Lint
        run: pnpm run lint

      - name: 🔨 Build
        run: pnpm run build

      - name: 🧑‍🏫 Build Example Project
        run: pnpm run --filter @this/example build

      - name: 🕵️ Check Package Configuration
        run: pnpm run check:package

      - name: 🧪 Test
        run: |
          pnpm dlx playwright install chromium
          pnpm run test:ci

      - name: 🛫 Upload Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          directory: ./coverage

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
